package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetContestsCidRankingHandlerFunc turns a function with the right signature into a get contests cid ranking handler
type GetContestsCidRankingHandlerFunc func(GetContestsCidRankingParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetContestsCidRankingHandlerFunc) Handle(params GetContestsCidRankingParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetContestsCidRankingHandler interface for that can handle valid get contests cid ranking params
type GetContestsCidRankingHandler interface {
	Handle(GetContestsCidRankingParams, interface{}) middleware.Responder
}

// NewGetContestsCidRanking creates a new http.Handler for the get contests cid ranking operation
func NewGetContestsCidRanking(ctx *middleware.Context, handler GetContestsCidRankingHandler) *GetContestsCidRanking {
	return &GetContestsCidRanking{Context: ctx, Handler: handler}
}

/*GetContestsCidRanking swagger:route GET /contests/{cid}/ranking getContestsCidRanking

Get ranking

*/
type GetContestsCidRanking struct {
	Context *middleware.Context
	Handler GetContestsCidRankingHandler
}

func (o *GetContestsCidRanking) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewGetContestsCidRankingParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
