package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cs3238-tsuzu/popcon-sc/ranking/models"
)

/*GetContestsCidRankingOK Successful response

swagger:response getContestsCidRankingOK
*/
type GetContestsCidRankingOK struct {

	/*
	  In: Body
	*/
	Payload []*models.RankingRow `json:"body,omitempty"`
}

// NewGetContestsCidRankingOK creates GetContestsCidRankingOK with default headers values
func NewGetContestsCidRankingOK() *GetContestsCidRankingOK {
	return &GetContestsCidRankingOK{}
}

// WithPayload adds the payload to the get contests cid ranking o k response
func (o *GetContestsCidRankingOK) WithPayload(payload []*models.RankingRow) *GetContestsCidRankingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get contests cid ranking o k response
func (o *GetContestsCidRankingOK) SetPayload(payload []*models.RankingRow) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContestsCidRankingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.RankingRow, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetContestsCidRankingBadRequest Bad request (Invalid Contest ID)

swagger:response getContestsCidRankingBadRequest
*/
type GetContestsCidRankingBadRequest struct {
}

// NewGetContestsCidRankingBadRequest creates GetContestsCidRankingBadRequest with default headers values
func NewGetContestsCidRankingBadRequest() *GetContestsCidRankingBadRequest {
	return &GetContestsCidRankingBadRequest{}
}

// WriteResponse to the client
func (o *GetContestsCidRankingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

/*GetContestsCidRankingForbidden Access denied. Your authentication is wrong.

swagger:response getContestsCidRankingForbidden
*/
type GetContestsCidRankingForbidden struct {
}

// NewGetContestsCidRankingForbidden creates GetContestsCidRankingForbidden with default headers values
func NewGetContestsCidRankingForbidden() *GetContestsCidRankingForbidden {
	return &GetContestsCidRankingForbidden{}
}

// WriteResponse to the client
func (o *GetContestsCidRankingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

/*GetContestsCidRankingInternalServerError Internal server error

swagger:response getContestsCidRankingInternalServerError
*/
type GetContestsCidRankingInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetContestsCidRankingInternalServerError creates GetContestsCidRankingInternalServerError with default headers values
func NewGetContestsCidRankingInternalServerError() *GetContestsCidRankingInternalServerError {
	return &GetContestsCidRankingInternalServerError{}
}

// WithPayload adds the payload to the get contests cid ranking internal server error response
func (o *GetContestsCidRankingInternalServerError) WithPayload(payload string) *GetContestsCidRankingInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get contests cid ranking internal server error response
func (o *GetContestsCidRankingInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContestsCidRankingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
