package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*GetContestsCidJoinUIDOK Succesful response

swagger:response getContestsCidJoinUidOK
*/
type GetContestsCidJoinUIDOK struct {

	/*
	  In: Body
	*/
	Payload bool `json:"body,omitempty"`
}

// NewGetContestsCidJoinUIDOK creates GetContestsCidJoinUIDOK with default headers values
func NewGetContestsCidJoinUIDOK() *GetContestsCidJoinUIDOK {
	return &GetContestsCidJoinUIDOK{}
}

// WithPayload adds the payload to the get contests cid join Uid o k response
func (o *GetContestsCidJoinUIDOK) WithPayload(payload bool) *GetContestsCidJoinUIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get contests cid join Uid o k response
func (o *GetContestsCidJoinUIDOK) SetPayload(payload bool) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetContestsCidJoinUIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetContestsCidJoinUIDForbidden Access denied. Your authentication is wrong.

swagger:response getContestsCidJoinUidForbidden
*/
type GetContestsCidJoinUIDForbidden struct {
}

// NewGetContestsCidJoinUIDForbidden creates GetContestsCidJoinUIDForbidden with default headers values
func NewGetContestsCidJoinUIDForbidden() *GetContestsCidJoinUIDForbidden {
	return &GetContestsCidJoinUIDForbidden{}
}

// WriteResponse to the client
func (o *GetContestsCidJoinUIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}
