package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostShutdownHandlerFunc turns a function with the right signature into a post shutdown handler
type PostShutdownHandlerFunc func(PostShutdownParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostShutdownHandlerFunc) Handle(params PostShutdownParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostShutdownHandler interface for that can handle valid post shutdown params
type PostShutdownHandler interface {
	Handle(PostShutdownParams, interface{}) middleware.Responder
}

// NewPostShutdown creates a new http.Handler for the post shutdown operation
func NewPostShutdown(ctx *middleware.Context, handler PostShutdownHandler) *PostShutdown {
	return &PostShutdown{Context: ctx, Handler: handler}
}

/*PostShutdown swagger:route POST /shutdown postShutdown

Shutdown this server

*/
type PostShutdown struct {
	Context *middleware.Context
	Handler PostShutdownHandler
}

func (o *PostShutdown) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPostShutdownParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
