package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*PostContestsRemoveCidOK Successful response

swagger:response postContestsRemoveCidOK
*/
type PostContestsRemoveCidOK struct {
}

// NewPostContestsRemoveCidOK creates PostContestsRemoveCidOK with default headers values
func NewPostContestsRemoveCidOK() *PostContestsRemoveCidOK {
	return &PostContestsRemoveCidOK{}
}

// WriteResponse to the client
func (o *PostContestsRemoveCidOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*PostContestsRemoveCidBadRequest Bad request

swagger:response postContestsRemoveCidBadRequest
*/
type PostContestsRemoveCidBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostContestsRemoveCidBadRequest creates PostContestsRemoveCidBadRequest with default headers values
func NewPostContestsRemoveCidBadRequest() *PostContestsRemoveCidBadRequest {
	return &PostContestsRemoveCidBadRequest{}
}

// WithPayload adds the payload to the post contests remove cid bad request response
func (o *PostContestsRemoveCidBadRequest) WithPayload(payload string) *PostContestsRemoveCidBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post contests remove cid bad request response
func (o *PostContestsRemoveCidBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostContestsRemoveCidBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*PostContestsRemoveCidForbidden Access denied. Your authentication is wrong.

swagger:response postContestsRemoveCidForbidden
*/
type PostContestsRemoveCidForbidden struct {
}

// NewPostContestsRemoveCidForbidden creates PostContestsRemoveCidForbidden with default headers values
func NewPostContestsRemoveCidForbidden() *PostContestsRemoveCidForbidden {
	return &PostContestsRemoveCidForbidden{}
}

// WriteResponse to the client
func (o *PostContestsRemoveCidForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

/*PostContestsRemoveCidInternalServerError Internal server error

swagger:response postContestsRemoveCidInternalServerError
*/
type PostContestsRemoveCidInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostContestsRemoveCidInternalServerError creates PostContestsRemoveCidInternalServerError with default headers values
func NewPostContestsRemoveCidInternalServerError() *PostContestsRemoveCidInternalServerError {
	return &PostContestsRemoveCidInternalServerError{}
}

// WithPayload adds the payload to the post contests remove cid internal server error response
func (o *PostContestsRemoveCidInternalServerError) WithPayload(payload string) *PostContestsRemoveCidInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post contests remove cid internal server error response
func (o *PostContestsRemoveCidInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostContestsRemoveCidInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
