package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostContestsRemoveCidHandlerFunc turns a function with the right signature into a post contests remove cid handler
type PostContestsRemoveCidHandlerFunc func(PostContestsRemoveCidParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostContestsRemoveCidHandlerFunc) Handle(params PostContestsRemoveCidParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostContestsRemoveCidHandler interface for that can handle valid post contests remove cid params
type PostContestsRemoveCidHandler interface {
	Handle(PostContestsRemoveCidParams, interface{}) middleware.Responder
}

// NewPostContestsRemoveCid creates a new http.Handler for the post contests remove cid operation
func NewPostContestsRemoveCid(ctx *middleware.Context, handler PostContestsRemoveCidHandler) *PostContestsRemoveCid {
	return &PostContestsRemoveCid{Context: ctx, Handler: handler}
}

/*PostContestsRemoveCid swagger:route POST /contests/remove/{cid} postContestsRemoveCid

Remove the ranking for the contest


*/
type PostContestsRemoveCid struct {
	Context *middleware.Context
	Handler PostContestsRemoveCidHandler
}

func (o *PostContestsRemoveCid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPostContestsRemoveCidParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
