package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*PostContestsCreateIDOK Successful response

swagger:response postContestsCreateIdOK
*/
type PostContestsCreateIDOK struct {
}

// NewPostContestsCreateIDOK creates PostContestsCreateIDOK with default headers values
func NewPostContestsCreateIDOK() *PostContestsCreateIDOK {
	return &PostContestsCreateIDOK{}
}

// WriteResponse to the client
func (o *PostContestsCreateIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*PostContestsCreateIDBadRequest Bad request

swagger:response postContestsCreateIdBadRequest
*/
type PostContestsCreateIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostContestsCreateIDBadRequest creates PostContestsCreateIDBadRequest with default headers values
func NewPostContestsCreateIDBadRequest() *PostContestsCreateIDBadRequest {
	return &PostContestsCreateIDBadRequest{}
}

// WithPayload adds the payload to the post contests create Id bad request response
func (o *PostContestsCreateIDBadRequest) WithPayload(payload string) *PostContestsCreateIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post contests create Id bad request response
func (o *PostContestsCreateIDBadRequest) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostContestsCreateIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*PostContestsCreateIDInternalServerError Internal server error

swagger:response postContestsCreateIdInternalServerError
*/
type PostContestsCreateIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostContestsCreateIDInternalServerError creates PostContestsCreateIDInternalServerError with default headers values
func NewPostContestsCreateIDInternalServerError() *PostContestsCreateIDInternalServerError {
	return &PostContestsCreateIDInternalServerError{}
}

// WithPayload adds the payload to the post contests create Id internal server error response
func (o *PostContestsCreateIDInternalServerError) WithPayload(payload string) *PostContestsCreateIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post contests create Id internal server error response
func (o *PostContestsCreateIDInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostContestsCreateIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
