package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// PostContestsRemoveCidURL generates an URL for the post contests remove cid operation
type PostContestsRemoveCidURL struct {
	Cid int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PostContestsRemoveCidURL) WithBasePath(bp string) *PostContestsRemoveCidURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PostContestsRemoveCidURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *PostContestsRemoveCidURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/contests/remove/{cid}"

	cid := swag.FormatInt64(o.Cid)
	if cid != "" {
		_path = strings.Replace(_path, "{cid}", cid, -1)
	} else {
		return nil, errors.New("Cid is required on PostContestsRemoveCidURL")
	}
	_basePath := o._basePath
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *PostContestsRemoveCidURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *PostContestsRemoveCidURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *PostContestsRemoveCidURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on PostContestsRemoveCidURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on PostContestsRemoveCidURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *PostContestsRemoveCidURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
