package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*PostContestsCidUpdateOK Successful response

swagger:response postContestsCidUpdateOK
*/
type PostContestsCidUpdateOK struct {
}

// NewPostContestsCidUpdateOK creates PostContestsCidUpdateOK with default headers values
func NewPostContestsCidUpdateOK() *PostContestsCidUpdateOK {
	return &PostContestsCidUpdateOK{}
}

// WriteResponse to the client
func (o *PostContestsCidUpdateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

/*PostContestsCidUpdateForbidden Access denied. Your authentication is wrong.

swagger:response postContestsCidUpdateForbidden
*/
type PostContestsCidUpdateForbidden struct {
}

// NewPostContestsCidUpdateForbidden creates PostContestsCidUpdateForbidden with default headers values
func NewPostContestsCidUpdateForbidden() *PostContestsCidUpdateForbidden {
	return &PostContestsCidUpdateForbidden{}
}

// WriteResponse to the client
func (o *PostContestsCidUpdateForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

/*PostContestsCidUpdateInternalServerError Internal server error

swagger:response postContestsCidUpdateInternalServerError
*/
type PostContestsCidUpdateInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostContestsCidUpdateInternalServerError creates PostContestsCidUpdateInternalServerError with default headers values
func NewPostContestsCidUpdateInternalServerError() *PostContestsCidUpdateInternalServerError {
	return &PostContestsCidUpdateInternalServerError{}
}

// WithPayload adds the payload to the post contests cid update internal server error response
func (o *PostContestsCidUpdateInternalServerError) WithPayload(payload string) *PostContestsCidUpdateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post contests cid update internal server error response
func (o *PostContestsCidUpdateInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostContestsCidUpdateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
