package swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostContestsCreateCidHandlerFunc turns a function with the right signature into a post contests create cid handler
type PostContestsCreateCidHandlerFunc func(PostContestsCreateCidParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostContestsCreateCidHandlerFunc) Handle(params PostContestsCreateCidParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostContestsCreateCidHandler interface for that can handle valid post contests create cid params
type PostContestsCreateCidHandler interface {
	Handle(PostContestsCreateCidParams, interface{}) middleware.Responder
}

// NewPostContestsCreateCid creates a new http.Handler for the post contests create cid operation
func NewPostContestsCreateCid(ctx *middleware.Context, handler PostContestsCreateCidHandler) *PostContestsCreateCid {
	return &PostContestsCreateCid{Context: ctx, Handler: handler}
}

/*PostContestsCreateCid swagger:route POST /contests/create/{cid} postContestsCreateCid

Create a ranking for the contest


*/
type PostContestsCreateCid struct {
	Context *middleware.Context
	Handler PostContestsCreateCidHandler
}

func (o *PostContestsCreateCid) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPostContestsCreateCidParams()

	uprinc, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
